export const
AUTHENTICATE = "ducks/session/AUTHENTICATE",
RESET_SESSION = "ducks/session/RESET_SESSION",
SET_TOKEN = "ducks/session/SET_TOKEN",
VALIDATE_TOKEN = "ducks/session/VALIDATE_TOKEN",
INITIALIZATION_COMPLETED = "duck/session/INITIALIZATION_COMPLETED",
RESET_TOKEN = "ducks/session/RESET_TOKEN",
FETCH_USER_DATA_WITH_TOKEN = "ducks/session/FETCH_USER_DATA_WITH_TOKEN",
FETCH_ACCOUNT_WITH_TOKEN = "ducks/session/FETCH_ACCOUNT_WITH_TOKEN",
FETCH_IDENTITY_WITH_TOKEN = "ducks/session/FETCH_IDENTITY_WITH_TOKEN",
SET_USER_DATA = "ducks/session/SET_USER_DATA"
